language: python
python:
    - "3.8"

services:
    - docker
<<<<<<< HEAD

before_script: pip install docker-compose

script:
    - docker-compose up
=======
script:
    - echo "skipping tests"
>>>>>>> e681caa99e8087f402dd05fe663984f2fde7c479
