<<<<<<< HEAD
version: "3.3"


services:
    app:
        build:
            context: . 
        ports:
            - "5000:5000"
       
        command: >
            sh -c "python manage.py wait_for_db && 
                   python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:5000"
     
=======
version: '3.3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
>>>>>>> e681caa99e8087f402dd05fe663984f2fde7c479
